name: iOS CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main, development ]
jobs:
  build:
    runs-on: macos-26
    permissions:
      contents: read
    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0  # v7.0.0
    - uses: maxim-lobanov/setup-xcode@ed7a3b1fda3918c0306d1b724322adc0b8cc0a90  # v1
      with:
        xcode-version: '26.2'
    - name: Run Test
      working-directory: MixpanelSessionReplay
      run: |
        set -o pipefail
        xcodebuild -scheme MixpanelSessionReplay -derivedDataPath Build/ -destination "name=iPhone 17,OS=26.2" -configuration Debug ONLY_ACTIVE_ARCH=NO ENABLE_TESTABILITY=YES -enableCodeCoverage YES clean build test | xcpretty -c;
